name: py2sambvca-rtd
channels:
  - conda-forge
dependencies:
  - python 3.9
  - notebook
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
      - pytest-cov
      - sphinx
      - sphinx-click
      - sphinx_rtd_theme
      - nbsphinx
      - nbsphinx-link
      - m2r2
      - ..
